title = "JapanAds Base"
description = "不快な広告/ポスターを消すフィルター"
maintainer = "kurinkurin2355"

[[block]]
friendly_name = "[JP]Tutorial world"
world_id = "wrld_bf51e60f-f372-48b1-a757-88ba8331d926"
game_objects = [
    # 入り口
    { name = "Adv_Entrance" },
    { name = "Adv_Entrance (1)" },
    { name = "Adv_Entrance (2)" },
    # 正面ミラー
    { name = "Adver_MirrorSwitchLeft" },
    { name = "Adver_MirrorSwitchRight" },
    { name = "Adver_BackMirror01" },
    { name = "Adver_BackMirror02" },
    { name = "Adver_BackMirror03" },
    { name = "Adver_BackMirror04" },
    { name = "Adver_BackMirror05" },
    # 正面右はしご
    { name = "Advertisement" },
    # 正面左
    { name = "Adver_Monthly_2" },
    { name = "Adver_SideMirror01" },
    { name = "Adver_SideMirror02" },
    { name = "Adver_SideMirror03" },
    # アバター
    { name = "Adver_SideMirror04" },
    # ローカル/グローバル
    { name = "Adv_Ladder01 (4)" },
]

[[block]]
friendly_name = "日本語話者向け集会場「FUJIYAMA」JP"
world_id = "wrld_f5f8b3dc-6f33-4b34-97f3-83add2fb224d"
game_objects = [
    { name = "ポスター" },
    { name = "右ポスター" },
    { name = "左ポスター" },
]

[[block]]
friendly_name = "しるきーはいつ"
world_id = "wrld_3d05eded-b1bb-4c5c-839f-08dc00006640"
game_objects = [
    { name = "ポスター" },
]

[[block]]
friendly_name = "カラオケワールド JP KARAOKE"
world_id = "wrld_2054fa71-8e72-4c93-9040-f174f71fab2e"
game_objects = [
    { name = "_posters" },
    { name = "_posters (1)" },
]

[[block]]
friendly_name = "Japan Talk Room 日本人向け談話室 [ JTR JP ]"
world_id = "wrld_175f8d7d-fd44-476a-8242-8aaef5ba5b33"
game_objects = [
    { name = "Poster" },
]

[[block]]
friendly_name = "【JP】 Qじゃぱんひろば（UDON）"
world_id = "wrld_dd48dfb4-304e-4b2f-a470-2d7fb79be98f"
game_objects = [
    # ネットワーク広告
    { name = "VRC-ADVirth" },
    { name = "VRAd"},
    # 自己宣伝
    { name = "Plane", position = { x = -0.654, y = -0.055, z = 0 } },
    { name = "Plane (2)", position = { x = -37.88, y = -0.34, z = -11.3 } },
]

[[block]]
friendly_name = "［JP］ USiOPORT ウシヲポート"
world_id = "wrld_3d12fbc0-c470-4e97-9191-3cf3aeba8832"
game_objects = [
    { name = "Posters (UDON)"},
    { name = "FreePR"},
    { name = "イベントエリア行き止まり"},
    # "ポスター"内の広告
    { name = "Quad (2)" },
    { name = "Quad (4)" },
    { name = "Quad (33)", position = { x = -7.52 , y = 1.17 , z = 6.263 } },
    { name = "Quad (68)" },
    { name = "Quad (43)" },
    { name = "Quad (54)" },
    { name = "Quad (55)" },
    { name = "Quad (37)" },
    { name = "Quad (38)" },
    { name = "Quad (63)" },
    { name = "Quad (65)" },
    { name = "Quad (69)" },
    { name = "Quad (57)" },
    { name = "Quad (70)" },
    { name = "Quad (40)" },
    { name = "Quad (41)" },
    { name = "Quad (44)" },
    { name = "Quad (45)" },
    # ２階広告
    { name = "Radio", parent = { name = "USiOPORT" } },
    # vrc放送局テレビ
    { name = "VRCTV-TV" },
]

[[block]]
friendly_name = "ポピー横丁-Poppy Street-"
world_id = "wrld_30716c54-3565-42f7-b7c5-d398ef4faac5"
game_objects = [
    { name = "StreetPoster" },
    # 音楽を無効化
    { name = "WorldBGM" },
]
